Create pull_request_template.md
uw-ssec/python-project-template pull request #10
Opened 2023-04-12 17:20 UTC by uwcdc

Create PR template for the Python template. Please review @carlosgjs @lsetiawan and let me know what changes need to be made.

https://github.com/uw-ssec/python-project-template/issues/8

2023-04-12 18:45 UTC, carlosgjs reviewed
Looking good. I added some questions/suggestions inline.

2023-04-12 18:45 UTC, carlosgjs commented on .github/pull_request_template.md
> +- [] <link _to_the_issue_that_the_PR_fixes>
I suggest making the language more general so that it encompasses any type of change (e.g. feature work)
```suggestion
## Change Description (or Root Cause)
- [] <link _to_the_issue_that_the_PR_addresses>
```

2023-04-12 18:45 UTC, carlosgjs commented on .github/pull_request_template.md
> +- [] Provide a list of external packages/dependencies used in your solution
Wouldn't the external dependencies show up in the diffs? E.g. `requirements.txt/pyproject.toml/conda.yml`, `go.mod`, `packages.json`, etc?

2023-04-12 18:45 UTC, carlosgjs commented on .github/pull_request_template.md
> +- [] You are using approved terminology
What constitutes approved terminology? I think I would have a hard time answering this question without more context

2023-04-12 18:45 UTC, carlosgjs commented on .github/pull_request_template.md
> +- [] Provide a list of the test packages/dependencies used
similar question as above regarding dependencies

2023-04-12 21:14 UTC, uwcdc commented on .github/pull_request_template.md
> +- [] Provide a list of external packages/dependencies used in your solution
That makes sense! I will eliminate that check.

2023-04-12 21:15 UTC, uwcdc commented on .github/pull_request_template.md
> +- [] You are using approved terminology
I was just thinking about industry-standard terminology and notations. This shouldn't be a problem for us, but I was thinking about the case where an undergrad or junior dev is contributing.

2023-04-12 21:16 UTC, uwcdc commented on .github/pull_request_template.md
> +- [] Provide a list of the test packages/dependencies used
Makes sense. I will eliminate this checklist item as well.

2023-04-12 22:26 UTC, carlosgjs commented on .github/pull_request_template.md
> +- [] You are using approved terminology
Right, I guess that's my concern. If I'm a junior dev, how would I know if I'm using approved terminology? I wonder if this can be removed from the checklist and then covered through the code review.

2023-04-13 20:42 UTC, uwcdc commented on .github/pull_request_template.md
> +- [] You are using approved terminology
Gotcha! I will just delete it for now, and if we have any issues with it, then we can deal with it on a case by case basis.

2023-04-13 20:56 UTC, uwcdc reviewed
@carlosgjs @lsetiawan Does the current version reflect your changes?

2023-04-13 23:06 UTC, lsetiawan commented on .github/pull_request_template.md
> +- [] Link to the PR you are addressing
```suggestion
- [ ] Link to the PR you are addressing
```

2023-04-13 23:06 UTC, lsetiawan commented on .github/pull_request_template.md
> +- [] Link to the PR you are addressing
Please fix the checkbox syntax

2023-04-13 23:06 UTC, lsetiawan commented on oryx-build-commands.txt
> +BuildCommands=conda env create --file environment.yml --prefix ./venv --quiet
What is this file for?

2023-04-13 23:10 UTC, lsetiawan requested changes
There are some fixes and questions I have above in comments. 

Another thing about the functionality of this, where will the developer fill out with the comments of the changes that occurred within the pull request? Should these be under the sections that you have laid out?

2024-06-10 17:10 UTC, closed without merging